$mod = ALT_SHIFT

bind = $mod, R, submap, rthemans

bindm = ALT, mouse:272, movewindow
bindm = ALT , mouse:273, resizewindow

submap = rthemans

# -- Navigation fenêtres
binde = , h, movefocus, l
binde = , l, movefocus, r
binde = , k, movefocus, u
binde = , j, movefocus, d
binde = , n, cyclenext, next
binde = SHIFT, n, cyclenext, prev

# -- Déplacement de fenêtres
bind = SHIFT, h, movewindow, l
bind = SHIFT, l, movewindow, r
bind = SHIFT, k, movewindow, u
bind = SHIFT, j, movewindow, d

# -- Actions fenêtres
bind = , Q, killactive, 
# chagpt disait de mettre toggle en param mais je pense qu’il se trompe
bind = , F, fullscreen,
bind = , SPACE, togglefloating,

# -- utils
bind = , S, exec, anyrun
bind = , S, submap, reset

# -- Workspaces
bind = , 1, workspace, 1
bind = , 1, submap, reset
bind = , 2, workspace, 2
bind = , 2, submap, reset
bind = , 3, workspace, 3
bind = , 3, submap, reset
bind = , 4, workspace, 4
bind = , 4, submap, reset
binde = , W, workspace, +1
binde = SHIFT, W, workspace, -1

# -- Déplacer vers workspace
bind = SHIFT, 1, movetoworkspace, 1
bind = SHIFT, 1, submap, reset
bind = SHIFT, 2, movetoworkspace, 2
bind = SHIFT, 2, submap, reset
bind = SHIFT, 3, movetoworkspace, 3
bind = SHIFT, 3, submap, reset
bind = SHIFT, 4, movetoworkspace, 4
bind = SHIFT, 4, submap, reset

# -- Workspaces spéciaux
bind = , S, togglespecialworkspace, scratch
bind = , S, submap, reset
bind = SHIFT, S, movetoworkspace, special:scratch
bind = SHIFT, S, submap, reset

# -- Reload (reste dans submap)
bind = SHIFT, R, reload

# -- Quitter le submap
bind = , ESCAPE, submap, reset
bind = $mod, R, submap, reset

submap = reset
