# this file contains my rules

layerrule = blur on, match:namespace walker

windowrule {
  name = move-kitty
  match:class = kitty

  move = 100 100
  animation = slide
}

windowrule {
    name = steam-app
    match:class = steam_app.*

    fullscreen = on
    monitor = desc:AOC
    workspace = 3
}
