# Lancement automatique
exec-once = systemctl --user start hyprpolkitagent
exec-once = elephant -d

# Moniteurs
monitor = desc:AOC, 1920x1080@239.96, 0x0, 1
monitor = desc:BNQ, 1920x1080@60.00, 1920x0, 1
workspace = 1, monitor:desc:AOC
exec-once = hyprctl dispatch workspace 1

# Configuration clavier
input {
    kb_layout = fr
    kb_variant = bepo
}

env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = WLR_DRM_DEVICES,/dev/dri/card0
env = WLR_RENDERER,vulkan
env = WLS_BACKENDS=drm
env = XDG_SESSION_TYPE,wayland
env = SDL_VIDEODRIVER,wayland
