# media keys
bindel = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bindel = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindl = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

# cycle through
binde = ALT CTRL , code:23, cyclenext, visible next
binde = ALT CTRL SHIFT , code:23, cyclenext, visible prev 
binde = ALT , code:23, cyclenext, next
binde = ALT SHIFT , code:23, cyclenext, prev 
binde = SUPER, code:23, workspace, e+1
binde = SUPER SHIFT, code:23, workspace, e-1
binde = SUPER, N, workspace, empty

# mouse mouvments
bindm = ALT, mouse:272, movewindow
bindm = ALT , mouse:273, resizewindow

# utils
bind = SUPER, L, exec, hyprlock
bind = ALT, code:70, killactive, 

# Programs
#bind = SUPER, SPACE, exec, walker
bind = SUPER, SPACE, global, caelestia:launcher
bind = SUPER SHIFT, s, exec, hyprshot --clipboard-only -m region

# Submaps
bind = SUPER, W, submap, WINDOWS
bind = SUPER, G, submap, GROUPS
bind = SUPER, v, submap, SOUND
bind = SUPER, p, submap, POWER

# movements
bind = SUPER, code:10, workspace, 1
bind = SUPER, code:11, workspace, 2
bind = SUPER, code:12, workspace, 3
bind = SUPER, code:13, workspace, 4
bind = SUPER, code:14, workspace, 5

# move to workspaces
bind = SUPER SHIFT, code:10, movetoworkspace, 1
bind = SUPER SHIFT, code:11, movetoworkspace, 2
bind = SUPER SHIFT, code:12, movetoworkspace, 3
bind = SUPER SHIFT, code:13, movetoworkspace, 4
bind = SUPER SHIFT, code:14, movetoworkspace, 5

# move something to monitor
bind = SUPER, code:113, focusmonitor, left
bind = SUPER SHIFT, code:113, movecurrentworkspacetomonitor, left
bind = SUPER, code:114, focusmonitor, right
bind = SUPER SHIFT, code:114, movecurrentworkspacetomonitor, right

bind = , code:95, fullscreen, 1
bind = SHIFT , code:95, fullscreen, 0
bind = SUPER SHIFT , SPACE, togglefloating,

submap = WINDOWS

# navigating windows
binde = , h, movefocus, l
binde = , l, movefocus, r
binde = , k, movefocus, u
binde = , j, movefocus, d
binde = , n, cyclenext, next
binde = SHIFT, n, cyclenext, prev

# moving windows
bind = SHIFT, h, movewindow, l
bind = SHIFT, l, movewindow, r
bind = SHIFT, k, movewindow, u
bind = SHIFT, j, movewindow, d
# -- grouping windows 
bind = SHIFT, G, togglegroup
bind = , N, changegroupactive, f
bind = SHIFT, N, changegroupactive, b
bind = ALT, L, moveintogroup, r
bind = ALT SHIFT , L, movewindoworgroup, r
bind = ALT, H, moveintogroup, l
bind = ALT SHIFT, H, movewindoworgroup, l
bind = ALT, K, moveintogroup, u
bind = ALT SHIFT , K, movewindoworgroup, u
bind = ALT, J, moveintogroup, d
bind = ALT SHIFT , J, movewindoworgroup, d
bind = , X, moveoutofgroup

# window actions
bind = , Q, killactive, 
bind = , F, fullscreen, 1
bind = SHIFT , F, fullscreen, 0
bind = SHIFT , SPACE, togglefloating,

bind = , ESCAPE, submap, reset
bind = , catchall, exec, notify-send "Press ESC to go in default"
submap = reset

submap = GROUPS
bind = , G, togglegroup
bind = , N, changegroupactive, f
bind = SHIFT, N, changegroupactive, b
bind = , L, moveintogroup, r
bind = SHIFT , L, movewindoworgroup, r
bind = , H, moveintogroup, l
bind = SHIFT, H, movewindoworgroup, l
bind = , X, moveoutofgroup

bind = , ESCAPE, submap, reset
bind = , catchall, exec, notify-send "Presc ESC to go in default"
submap = reset


submap = SOUND
# to find out how to have consistant ID or get them
# leave the submap
bindel = , K, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bindel = , J, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindl = , M, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

bind = , ESCAPE, submap, reset
bind = , catchall, exec, notify-send "Press ESC to go in default"
submap = reset


submap = POWER

bind = , R, exec, reboot
bind = , P, exec, poweroff

bind = , ESCAPE, submap, reset
bind = , catchall, exec, notify-send "Press ESC to go in default"
submap = reset

