windowrule {
    name = disable-idle
    match:class = steam_app.*

    idle_inhibit = always
}

windowrule {
    name = heroic
    match:class = heroic

    workspace = 4
}

windowrule {
    name = steam
    match:class = steam

    workspace = 4
}

windowrule {
    name = steam-app
    match:class = steam_app.*

    monitor = desc:AOC
    workspace = 4
}


windowrule {
    name = citrix
    match:class = Wfica

    tile = on
    monitor = desc:AOC
    workspace = 5
}

workspace = 1, on-created-empty:qutebrowser
workspace = 2, on-created-empty:kitty tmux new -As0
workspace = 3, on-created-empty:discord
