windowrule {
    name = disable-idle
    match:class = steam_app.*

    idle_inhibit = always
}

workspace = 1, on-created-empty:qutebrowser
workspace = 2, on-created-empty:kitty tmux new -As0
workspace = 3, on-created-empty:discord
