# this file contains my rules
## layer
layerrule = blur on, match:namespace walker

## window
windowrule {
  name = move-kitty
  match:class = kitty

  move = 100 100
  animation = slide
}

windowrule {
    name = steam-app
    match:class = steam_app.*

    fullscreen = on
    tile = on
    monitor = desc:AOC
    workspace = 3
}

## Workspace
workspace = 1, on-created-empty:firefox
workspace = 2, on-created-empty:kitty
workspace = 3, on-created-empty:steam
