exec-once = caelestia-shell
exec-once = nm-applet --indicator
exec-once = hyprlock
exec-once = systemctl --user start hyprpolkitagent
exec-once = swaync
exec-once = $HOME/.config/hypr/Scripts/layout-watch.sh
exec-once = $HOME/.config/hypr/Scripts/change-keyboard.sh "steam_app_default" "StarCraft II"
